/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package systemsoftware;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author shivu
 */
public class SS_GUI_1 extends javax.swing.JFrame {

    /**
     * Creates new form SS_GUI_1
     */

 C_Caller cl ;

    public SS_GUI_1() {
        super("PLSQL if else parser"); //name of window
        this.setLocation(300, 100); // location fro where cordinate starts 
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        initComponents(); //initalize components 

        cl = new  C_Caller() ;     

        filepath_display.setEditable(false);
        filepath_display.setText("selected file will be displayed here");
        cancle_button.setEnabled(false);
        cancle_button.setVisible(false);
        parse_button.setEnabled(false);
        parse_button.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        select_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        exit_button = new javax.swing.JButton();
        filepath_display = new java.awt.TextField();
        parse_button = new javax.swing.JButton();
        cancle_button = new javax.swing.JButton();
        setup_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 218, 201));
        jPanel1.setForeground(new java.awt.Color(228, 154, 123));

        jLabel1.setBackground(new java.awt.Color(201, 54, 65));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(13, 60, 202));
        jLabel1.setText("SYSTEM SOFTWARE");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(189, 25, 145));
        jLabel2.setText("PLSQL IF ELSE PARSER");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 34, 223));
        jLabel3.setText("______________________________________________________");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(200, 62, 147));
        jLabel4.setText("_____________________________________________________");

        select_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        select_button.setForeground(new java.awt.Color(38, 139, 179));
        select_button.setText("SELECT FILE");
        select_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_buttonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(46, 57, 229));
        jLabel5.setText("_________________________________________________________________");

        jLabel6.setText("A System Software project developed by  S SHIVAKUMAR  and SHASHANK HEGADE");

        jLabel7.setText("6th sem computer science department, SJCE, Mysuru.   year :2017");

        exit_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        exit_button.setForeground(new java.awt.Color(42, 141, 209));
        exit_button.setText("     EXIT    ");
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });

        filepath_display.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        filepath_display.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        parse_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        parse_button.setForeground(new java.awt.Color(43, 195, 51));
        parse_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parse_buttonActionPerformed(evt);
            }
        });

        cancle_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        cancle_button.setForeground(new java.awt.Color(247, 40, 56));
        cancle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancle_buttonActionPerformed(evt);
            }
        });

        setup_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        setup_button.setForeground(new java.awt.Color(59, 121, 156));
        setup_button.setText("   SETUP  ");
        setup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setup_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(setup_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exit_button))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cancle_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(parse_button))
                            .addComponent(filepath_display, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(90, 90, 90))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(select_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select_button)
                .addGap(27, 27, 27)
                .addComponent(filepath_display, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parse_button)
                    .addComponent(cancle_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit_button)
                    .addComponent(setup_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void select_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
         JFileChooser fileChooser = new JFileChooser();
        
              
          
         if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
         {
            java.io.File file = fileChooser.getSelectedFile() ;
            filepath_display.setText("");
            filepath_display.setText(file.getAbsolutePath());
            filename =  new String(file.getAbsolutePath()) ;
            if (!filename.endsWith(".txt") )
               {
                   JOptionPane.showMessageDialog(this, "not a valid file : please select .txt fromat");
                    return ;     
                }
            
            
         }
         else
         {  
             filename = "" ;
             JOptionPane.showMessageDialog(this, "file not selected");
             return ;    
         }
         
         
         //parse button setting
          parse_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          parse_button.setForeground(new java.awt.Color(43, 195, 51));
          parse_button.setText("PARSE FILE");
          parse_button.setEnabled(true);
          parse_button.setVisible(true);
         
         // cancel button setting
          cancle_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          cancle_button.setForeground(new java.awt.Color(247, 40, 56));
          cancle_button.setText("CANCLE");
          cancle_button.setEnabled(true);
          cancle_button.setVisible(true);
          
          
         select_button.setEnabled(false);
         select_button.setVisible(false);
         
    }                                             

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        this.dispose(); 
    }                                           

    private void cancle_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        select_button.setEnabled(true);
        select_button.setVisible(true);
        
        filename = "" ;
        
        cancle_button.setText("");
        cancle_button.setEnabled(false);
        cancle_button.setVisible(false);
        
        parse_button.setEnabled(false);
        parse_button.setText("");
        parse_button.setVisible(false);
        
        filepath_display.setText("");
        filepath_display.setText("selected file will be displayed here");
        
       
    }                                             

    private void parse_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        int result ;  
        
         if( filename.equalsIgnoreCase("")){
               JOptionPane.showMessageDialog(this,"file not selected");
        }
        

        Result_display r ;
        
         result = cl.callParser(filename) ;

        if(result == -1 ){
               JOptionPane.showMessageDialog(this,"internal error occured");
        }else if( result == 0){
              r = new Result_display() ;
              r.printSuccess();
              r.setVisible(true);
    
        }else {
               
              r = new Result_display() ;
              r.printFailure(result);
              r.setVisible(true);

            }
        
      

    }                                            

    private void setup_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
       
      
      //char[] cnm =  fnm.toCharArray() ;
      cl.initialSetup() ;
     
    }                                            
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("ubuntu".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SS_GUI_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SS_GUI_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SS_GUI_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SS_GUI_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SS_GUI_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton cancle_button;
    private javax.swing.JButton exit_button;
    private java.awt.TextField filepath_display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton parse_button;
    private javax.swing.JButton select_button;
    private javax.swing.JButton setup_button;
    // End of variables declaration                   
    private String filename ; 

   
   
}

class C_Caller
{

  static { 
      System.loadLibrary("C_Caller"); 
                                   
   } 
 public native  int initialSetup() ;
 public native  int callParser(String fname) ;

}

